title:            Tudor's blog
description:      (gamedev) curiosities <br/>with SCIENCE
disqus_shortname: deferred
#Your site's domain goes here. Leave localhost server or blank when working locally.
url:              http://blog.deferredreality.com
#url:              http://tdbe.github.io
#url:              http://localhost:8080/blog2

# Owner/author information
owner:
  name:           Tudor Berechet
  avatar:         avatar.png
  bio: 		  "Gamedev & we live in a game."
  bio1:            "Organic coder."
  bio2:			  "Likes immersion, disruption, futurism, VR, "
  bio3:           "PCG, volumes of volumes."
  # Social networking links used in footer. Update and remove as you like.
  facebook:       
  twitter:        CarnegieLemon
  bitbucket:      tdbe
  github:         tdbe
  email:           http://www.deferredreality.com/#resume
  stackexchange:  
  linkedin:       tudorberechet
  youtube:      https://www.youtube.com/channel/UCuZX7zGt0g51-TbmCGbECtA
  instagram:      
  flickr:         
  tumblr:         
  # For Google Authorship https://plus.google.com/authorship
  google_plus:   

# Background image to be tiled on all pages
background: 

# Analytics and webmaster tools stuff goes here
google_analytics: UA-55237302-1
google_verify:      
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:         

# Links to include in top navigation
# For external links add external: true
links:
#  - title: Theme Setup
#    url: /theme-setup
  - title: Portfolio
    url: http://www.deferredreality.com
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Berlin
future:      true
pygments:    true
markdown:    kramdown

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title/

# Amount of post to show on home page
paginate: 5

highlighter: rouge


kramdown:
  input:          GFM
  # https://github.com/jekyll/jekyll/pull/4090
  syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    css_class: 'highlight'
    #line_numbers: true
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
 # auto_ids: true
#  footnote_nr: 1
#  entity_output: as_char
 # toc_levels: 1..6
#  use_coderay: true
 # syntax_highlighter: rouge 
 # syntax_highlighter_opts:
#    default_lang: c
#    wrap: true
 #   block:
  #     line_numbers: true
 #      start_line: 1
#    inline_theme: colorful
       
  
  coderay:
    coderay_line_numbers: nil
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules"]